### ISSUE TITLE
prost-wkt-derive required

### ISSUE THREAD

**Issue by banool** [fdeantoni/prost-wkt#1]
Hi, I got here from https://github.com/danburkert/prost/issues/277. I'm trying to get serde json serialization working (no Any is okay).

When I follow the README, I get this error:
```
$ cargo build
    Updating git repository `https://github.com/fdeantoni/prost`
    Updating git repository `https://github.com/fdeantoni/prost-wkt`
    Updating crates.io index
error: no matching package named `prost-wkt-derive` found
location searched: https://github.com/fdeantoni/prost-wkt#9eb414fa
required by package `prost-wkt v0.1.0 (https://github.com/fdeantoni/prost-wkt#9eb4
14fa)`
    ... which is depended on by `team_heist_tactics v0.1.0 (/Users/dport/github/te
am_heist_tactics)`
```
I wonder if this is a private repo for you?

Thanks!

**Update**: I tried to pull the repo myself and build and it seems the `derive` directory and crate is missing.

**Comment by fdeantoni** [comment]
Sorry about that! For some reason my IDE was marking it as managed by remote but it was not! I just pushed the latest with the missing sub project. Let me know if it works properly now.

**Comment by banool** [comment]
That worked to fix this issue!

Saying that, it does not seem to succeed for my project. I've tried various permutations of the derives to add and the rename_all field and I always end up with one of these errors.

```
error: #[serde(default)] can only be used on structs with named fields
   --> /Users/dport/github/team_heist_tactics/target/debug/build/team_heist_tactics-295488de4f141a52/out/types.rs:157:5
    |
157 | pub enum HeisterColor {
    |     ^^^^
```
```
error: cannot find derive macro `Serialize` in this scope
   --> /Users/dport/github/team_heist_tactics/target/debug/build/team_heist_tactics-295488de4f141a52/out/types.rs:141:14
    |
141 |     #[derive(Serialize, Deserialize)] #[serde(default, rename_all="camelCase")]
    |              ^^^^^^^^^
```

This snippet isn't super helpful probably, so I've left these broken changes in prost_wkt_demonstration branch of https://github.com/banool/team_heist_tactics if you're interested. You would just have to `cargo build` to see the issue. If you want a minimal repro instead because it's too much work I'd be more than happy to try and make one.

See it here: https://github.com/banool/team_heist_tactics.

Thanks for your efforts here!

**Comment by fdeantoni** [comment]
No worries! Thanks for trying out this project. Your help already fixed some problems. 

I reviewed your project and it looks like you actually do not need to use `prost-wkt`. You can just use `prost` and `prost-types`. The `prost-wkt` cargo will only help if you use `Timestamp`, `Any`, and/or `Value`. If you don't use any of these, you can just use `prost-types` with some tweaking of the `build.rs` to achieve the same. In your case, your `build.rs` would look as follows:
```rust
fn main() {
    let mut prost_build = prost_build::Config::new();
    prost_build
	.type_attribute(".types.MainMessage.body", "use serde::{Serialize, Deserialize}; #[derive(Serialize, Deserialize)]")
	.type_attribute(".types.InvalidRequest", "#[derive(Serialize, Deserialize)]")
	.type_attribute(".types.Move", "#[derive(Serialize, Deserialize)]")
	.type_attribute(".types.GameState", "#[derive(Serialize, Deserialize)]")
	.type_attribute(".types.GameStatus", "#[derive(Serialize, Deserialize)]")
	.type_attribute(".types.Player", "#[derive(Serialize, Deserialize)]")
	.type_attribute(".types.Ability", "#[derive(Serialize, Deserialize)]")
	.type_attribute(".types.Heister", "#[derive(Serialize, Deserialize)]")
	.type_attribute(".types.WallType", "#[derive(Serialize, Deserialize)]")
	.type_attribute(".types.SquareType", "#[derive(Serialize, Deserialize)]")
	.type_attribute(".types.Square", "#[derive(Serialize, Deserialize)]")
	.type_attribute(".types.Tile", "#[derive(Serialize, Deserialize)]")
	.type_attribute(".types.MapPosition", "#[derive(Serialize, Deserialize)]")
	.type_attribute(".types.TilePosition", "#[derive(Serialize, Deserialize)]")
	.type_attribute(".types.HeisterName", "#[derive(Serialize, Deserialize)]")
	.type_attribute(".types.HeisterColor", "#[derive(Serialize, Deserialize)]")
        .compile_protos(
            &[
                "src/types.proto"
            ],
            &["src/"],
        )
        .unwrap();
}
```

Its a bit unwieldy as you need to define things per message since `type_attribute` does not support regexp or whatnot to define the message path.

With your `build.rs` as above, all you need to do is add the appropriate imports in your `src/types.rs` file as well, like so:
```rust
// Import all the proto types in this private module.
mod proto_types {
    use serde::{Deserialize, Serialize};
    include!(concat!(env!("OUT_DIR"), "/types.rs"));
}
```  

If you do the above, your project should compile fine (I have not tested it after that though).

I have updated the README of `prost-wkt` to describe the above limitations as well. Hope this helps!

**Comment by banool** [comment]
Amazing, that did the trick!! Thanks for updating the README too. Now to just get this merged in to prost proper 😄

**Comment by fdeantoni** [comment]
Great! I will go ahead and close this issue, but feel free to create a new one if something comes up...
