### ISSUE TITLE
Qualify derives

### ISSUE THREAD

**Issue by wagenet** [fdeantoni/prost-wkt#11]
Instead of doing `use serde::{Serialize ,Deserialize}` everywhere, can't we just do `#[derive(serde::Serialize, serde::Deserialize)]`? This would remove the need for the workaround here https://github.com/fdeantoni/prost-wkt#oneof-types.

**Comment by fdeantoni** [comment]
Addressed with commit [08f3487](https://github.com/fdeantoni/prost-wkt/commit/08f3487bb1432748eb7d0e80af0ddb499e79cb95).

**Comment by wagenet** [comment]
Thanks!
