### ISSUE TITLE
crates.io 0.3.3 missing?

### ISSUE THREAD

**Issue by dragonnn** [fdeantoni/prost-wkt#29]
As the title says, is they any reason 0.3.3 is not present on crates.io?
Not a big problem but just found out this when updating deps in my project and prost-wkt stopped working with prost 0.11.
Switched for now to git with patch.crates.io

**Comment by fdeantoni** [comment]
It has not been released yet, but it will be in the next few days!

**Comment by dragonnn** [comment]
Ah, thanks! Wrongly assumed it is just a mistake. Looking forward to it :)
