### ISSUE TITLE
Empty is missing

### ISSUE THREAD

**Issue by alexthe2** [fdeantoni/prost-wkt#30]
`google.protobuf.Empty` is currently not a well-known-type

workaround for now: create an empty message 🙃

**Comment by fdeantoni** [comment]
That's an interesting one! Let me check how best to include it.

**Comment by fdeantoni** [comment]
I have added the Empty message which I can release under 0.4.1. Hope this addresses it correctly, but if not do let me know!

**Comment by alexthe2** [comment]
Thanks, will check it out

**Comment by fdeantoni** [comment]
Released with v0.4.1.
