### ISSUE TITLE
Updating to prost-wkt 0.5 can break downstream builds

### ISSUE THREAD

**Issue by jorendorff** [fdeantoni/prost-wkt#58]
I had an existing project using `prost-wkt` 0.4 with `chrono` 0.4.24. When I updated to `prost-wkt` 0.5, the build broke because `DateTime::from_naive_utc_and_offset` is not in that version of `chrono`. The fix for my project was `cargo update -p chrono`, but this will bite others too.

I think the right fix is to change `Cargo.toml` to insist on a version of `chrono` that is recent enough to use. `chrono = "0.4.31"` would select the version that's current right now.

**Comment by fdeantoni** [comment]
Thanks for raising this issue! This is a good catch. I will update the Cargo.toml to better specify the dependency of chrono. Will aim to release it in 0.5.1 within next week.

**Comment by fdeantoni** [comment]
I released v0.5.1 which uses chrono 0.4.27 which contains DateTime::from_naive_utc_and_offset. Let me know if this release works well for you.
